# Xamarin
# Build a Xamarin project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
  branches:
    include:
      - master
pr:
  - master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

# To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
# https://go.microsoft.com/fwlink/?linkid=871629
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_4_2
  displayName: 'Select Xamarin SDK version'
  enabled: false

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    msbuildArchitectureOption: 'x86'
    clean: true
    jdkOption: 'JDKVersion'
- task: XamariniOS@2
  inputs:
    solutionFile: '**/*iOS*.csproj'
    configuration: 'Release'
    clean: true
    packageApp: false
    buildForSimulator: true
    runNugetRestore: true